version: '3.9'

services:
  node:
    image: node
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run dev

  # web:
  #   image: nginx
  #   volumes:
  #     - ./:/usr/share/nginx/html
  #   ports:
  #     - 80:80
